#
# ################################################################################
#
# This file was automatically generated with ./gen/generate_module.py
#          Do not edit this file directly.
#          More information in repository README.md
#
# ################################################################################
#

output "ids" {
  description = "IDs of the objects managed by the module, by resource and object key (the ID for objects that exist once per ISE)."
  value = {
    active_directory_add_groups = merge(
      { for k, v in ise_active_directory_add_groups.active_directory_add_groups : k => v.id },
    )
    active_directory_join_domain_with_all_nodes = merge(
      { for k, v in ise_active_directory_join_domain_with_all_nodes.active_directory_join_domain_with_all_nodes : k => v.id },
    )
    active_directory_join_point = merge(
      { for k, v in ise_active_directory_join_point.active_directory_join_point : k => v.id },
    )
    allowed_protocols = merge(
      { for k, v in ise_allowed_protocols.allowed_protocols : k => v.id },
    )
    allowed_protocols_tacacs = merge(
      { for k, v in ise_allowed_protocols_tacacs.allowed_protocols_tacacs : k => v.id },
    )
    authorization_profile = merge(
      { for k, v in ise_authorization_profile.authorization_profile : k => v.id },
    )
    certificate_authentication_profile = merge(
      { for k, v in ise_certificate_authentication_profile.certificate_authentication_profile : k => v.id },
    )
    device_admin_authentication_rule = merge(
      { for k, v in ise_device_admin_authentication_rule.device_admin_authentication_rule : k => v.id },
    )
    device_admin_authorization_exception_rule = merge(
      { for k, v in ise_device_admin_authorization_exception_rule.device_admin_authorization_exception_rule : k => v.id },
    )
    device_admin_authorization_global_exception_rule = merge(
      { for k, v in ise_device_admin_authorization_global_exception_rule.device_admin_authorization_global_exception_rule : k => v.id },
    )
    device_admin_authorization_rule = merge(
      { for k, v in ise_device_admin_authorization_rule.device_admin_authorization_rule : k => v.id },
    )
    device_admin_condition = merge(
      { for k, v in ise_device_admin_condition.device_admin_condition : k => v.id },
      { for k, v in ise_device_admin_condition.device_admin_condition_tier1 : k => v.id },
      { for k, v in ise_device_admin_condition.device_admin_condition_tier2 : k => v.id },
      { for k, v in ise_device_admin_condition.device_admin_condition_tier3 : k => v.id },
    )
    device_admin_policy_set = merge(
      { for k, v in ise_device_admin_policy_set.device_admin_policy_set : k => v.id },
    )
    device_admin_time_and_date_condition = merge(
      { for k, v in ise_device_admin_time_and_date_condition.device_admin_time_and_date_condition : k => v.id },
    )
    downloadable_acl = merge(
      { for k, v in ise_downloadable_acl.downloadable_acl : k => v.id },
    )
    endpoint = merge(
      { for k, v in ise_endpoint.endpoint : k => v.id },
    )
    endpoint_custom_attribute = merge(
      { for k, v in ise_endpoint_custom_attribute.endpoint_custom_attribute : k => v.id },
    )
    endpoint_identity_group = merge(
      { for k, v in ise_endpoint_identity_group.endpoint_identity_group : k => v.id },
      { for k, v in ise_endpoint_identity_group.endpoint_identity_group_tier1 : k => v.id },
      { for k, v in ise_endpoint_identity_group.endpoint_identity_group_tier2 : k => v.id },
      { for k, v in ise_endpoint_identity_group.endpoint_identity_group_tier3 : k => v.id },
    )
    identity_source_sequence = merge(
      { for k, v in ise_identity_source_sequence.identity_source_sequence : k => v.id },
    )
    internal_user = merge(
      { for k, v in ise_internal_user.internal_user : k => v.id },
    )
    license_tier_state = try(ise_license_tier_state.license_tier_state[0].id, null)
    network_access_authentication_rule = merge(
      { for k, v in ise_network_access_authentication_rule.network_access_authentication_rule : k => v.id },
    )
    network_access_authorization_exception_rule = merge(
      { for k, v in ise_network_access_authorization_exception_rule.network_access_authorization_exception_rule : k => v.id },
    )
    network_access_authorization_global_exception_rule = merge(
      { for k, v in ise_network_access_authorization_global_exception_rule.network_access_authorization_global_exception_rule : k => v.id },
    )
    network_access_authorization_rule = merge(
      { for k, v in ise_network_access_authorization_rule.network_access_authorization_rule : k => v.id },
    )
    network_access_condition = merge(
      { for k, v in ise_network_access_condition.network_access_condition : k => v.id },
      { for k, v in ise_network_access_condition.network_access_condition_tier1 : k => v.id },
      { for k, v in ise_network_access_condition.network_access_condition_tier2 : k => v.id },
      { for k, v in ise_network_access_condition.network_access_condition_tier3 : k => v.id },
    )
    network_access_dictionary = merge(
      { for k, v in ise_network_access_dictionary.network_access_dictionary : k => v.id },
    )
    network_access_dictionary_attribute = merge(
      { for k, v in ise_network_access_dictionary_attribute.network_access_dictionary_attribute : k => v.id },
    )
    network_access_policy_set = merge(
      { for k, v in ise_network_access_policy_set.network_access_policy_set : k => v.id },
    )
    network_access_time_and_date_condition = merge(
      { for k, v in ise_network_access_time_and_date_condition.network_access_time_and_date_condition : k => v.id },
    )
    network_device = merge(
      { for k, v in ise_network_device.network_device : k => v.id },
    )
    network_device_group = merge(
      { for k, v in ise_network_device_group.network_device_group : k => v.id },
    )
    repository = merge(
      { for k, v in ise_repository.repository : k => v.id },
    )
    sxp_connection = merge(
      { for k, v in ise_sxp_connection.sxp_connection : k => v.id },
    )
    sxp_domain_filter = merge(
      { for k, v in ise_sxp_domain_filter.sxp_domain_filter : k => v.id },
    )
    sxp_local_binding = merge(
      { for k, v in ise_sxp_local_binding.sxp_local_binding : k => v.id },
    )
    sxp_vpn = merge(
      { for k, v in ise_sxp_vpn.sxp_vpn : k => v.id },
    )
    tacacs_command_set = merge(
      { for k, v in ise_tacacs_command_set.tacacs_command_set : k => v.id },
    )
    tacacs_profile = merge(
      { for k, v in ise_tacacs_profile.tacacs_profile : k => v.id },
    )
    trustsec_egress_matrix_cell = merge(
      { for k, v in ise_trustsec_egress_matrix_cell.trustsec_egress_matrix_cell : k => v.id },
    )
    trustsec_egress_matrix_cell_default = try(ise_trustsec_egress_matrix_cell_default.trustsec_egress_matrix_cell_default[0].id, null)
    trustsec_egress_push_matrix         = try(ise_trustsec_egress_push_matrix.trustsec_egress_push_matrix[0].id, null)
    trustsec_ip_to_sgt_mapping = merge(
      { for k, v in ise_trustsec_ip_to_sgt_mapping.trustsec_ip_to_sgt_mapping : k => v.id },
    )
    trustsec_ip_to_sgt_mapping_group = merge(
      { for k, v in ise_trustsec_ip_to_sgt_mapping_group.trustsec_ip_to_sgt_mapping_group : k => v.id },
    )
    trustsec_matrix = merge(
      { for k, v in ise_trustsec_matrix.trustsec_matrix : k => v.id },
    )
    trustsec_security_group = merge(
      { for k, v in ise_trustsec_security_group.trustsec_security_group : k => v.id },
    )
    trustsec_security_group_acl = merge(
      { for k, v in ise_trustsec_security_group_acl.trustsec_security_group_acl : k => v.id },
    )
    trustsec_work_process_settings = try(ise_trustsec_work_process_settings.trustsec_work_process_settings[0].id, null)
    user_identity_group = merge(
      { for k, v in ise_user_identity_group.user_identity_group : k => v.id },
    )
  }
}
