#
# ################################################################################
#
# This file was automatically generated with ./gen/generate_module.py
#          Do not edit this file directly.
#          More information in repository README.md
#
# ################################################################################
#
#
# ==================================================================
# LICENSE TIER STATE
# ==================================================================
#
# | Attribute Name | Type | Required | Description |
# |--------------|------|----------|-------------|
# | licenses | List | True | List of licenses |
#
# YAML: ise.system.license_tier_state (single object)
#

locals {
  # Defaults for license tier state (module defaults merged with user defaults)
  defaults_license_tier_state = try(local.defaults.ise.system.license_tier_state, {})

  # License tier state objects with defaults
  license_tier_state = [for item in try([local.ise.system.license_tier_state], []) : merge(
    # defaults of nested lists apply to each list item
    { for k, v in local.defaults_license_tier_state : k => v if !contains(["licenses"], k) },
    item,
    { for k in ["licenses"] : k => [for i in item[k] : merge(try(local.defaults_license_tier_state[k], {}), i)] if try(item[k], null) != null }
  )]
}

resource "ise_license_tier_state" "license_tier_state" {
  count = length(local.license_tier_state)

  licenses = try(local.license_tier_state[count.index].licenses, null) == null ? null : [for i1 in local.license_tier_state[count.index].licenses : {
    name   = try(i1.name, null)
    status = try(i1.status, null)
  }]
}

#
# ==================================================================
# REPOSITORY
# ==================================================================
#
# | Attribute Name | Type | Required | Description |
# |--------------|------|----------|-------------|
# | name | String | True | Repository name should be less than 80 characters and can contain alphanumeric, underscore, hyphen and dot characters. |
# | protocol | String | True | Protocol |
# | path | String | True | Path should always start with \"/\" and can contain alphanumeric, underscore, hyphen and dot characters. |
# | server_name | String | False | Name of the server |
# | user_name | String | False | User name |
# | password | String | False | Password can contain alphanumeric and/or special characters. |
# | enable_pki | Bool | False | Enable PKI |
#
# YAML: ise.system.repository (list, objects identified by name)
#

locals {
  # Defaults for repository (module defaults merged with user defaults)
  defaults_repository = try(local.defaults.ise.system.repository, {})

  # Repository objects with defaults
  repository = [for item in try(local.ise.system.repository, []) : merge(
    local.defaults_repository,
    item
  )]
}

resource "ise_repository" "repository" {
  for_each = { for item in local.repository : item.name => item }

  name        = try(each.value.name, null)
  protocol    = try(each.value.protocol, null)
  path        = try(each.value.path, null)
  server_name = try(each.value.server_name, null)
  user_name   = try(each.value.user_name, null)
  password    = sensitive(try(each.value.password, null))
  enable_pki  = try(each.value.enable_pki, null)

  lifecycle {
    ignore_changes = [enable_pki]
  }
}
