#
# ################################################################################
#
# This file was automatically generated with ./gen/generate_module.py
#          Do not edit this file directly.
#          More information in repository README.md
#
# ################################################################################
#
#
# ==================================================================
# ACTIVE DIRECTORY ADD GROUPS
# ==================================================================
#
# | Attribute Name | Type | Required | Description |
# |--------------|------|----------|-------------|
# | join_point_id | String | False | Active Directory Join Point ID |
# | name | String | True | The name of the active directory join point |
# | description | String | False | Join point Description |
# | domain | String | True | AD domain associated with the join point |
# | ad_scopes_names | String | False | String that contains the names of the scopes that the active directory belongs to. Names are separated by comm |
# | enable_domain_allowed_list | Bool | False |  |
# | groups | List | False | List of AD Groups |
#
# YAML: ise.identity_management.active_directory_add_groups (list, objects identified by name)
#

locals {
  # Defaults for active directory add groups (module defaults merged with user defaults)
  defaults_active_directory_add_groups = try(local.defaults.ise.identity_management.active_directory_add_groups, {})

  # Active directory add groups objects with defaults
  active_directory_add_groups = [for item in try(local.ise.identity_management.active_directory_add_groups, []) : merge(
    # defaults of nested lists apply to each list item
    { for k, v in local.defaults_active_directory_add_groups : k => v if !contains(["groups"], k) },
    item,
    { for k in ["groups"] : k => [for i in item[k] : merge(try(local.defaults_active_directory_add_groups[k], {}), i)] if try(item[k], null) != null }
  )]
}

resource "ise_active_directory_add_groups" "active_directory_add_groups" {
  for_each = { for item in local.active_directory_add_groups : try(item.name, item.join_point_id, "") => item }

  join_point_id              = try(each.value.join_point_id, null) != null ? each.value.join_point_id : try(each.value.name, null) != null ? lookup(local.active_directory_join_point_ids, each.value.name, null) : null
  name                       = try(each.value.name, null)
  description                = try(each.value.description, null)
  domain                     = try(each.value.domain, null)
  ad_scopes_names            = try(each.value.ad_scopes_names, null)
  enable_domain_allowed_list = try(each.value.enable_domain_allowed_list, null)
  groups = try(each.value.groups, null) == null ? null : [for i1 in each.value.groups : {
    name = try(i1.name, null)
    sid  = try(i1.sid, null)
    type = try(i1.type, null)
  }]
}

#
# ==================================================================
# ACTIVE DIRECTORY JOIN DOMAIN WITH ALL NODES
# ==================================================================
#
# | Attribute Name | Type | Required | Description |
# |--------------|------|----------|-------------|
# | join_point_id | String | False | Active Directory Join Point ID |
# | additional_data | List | True |  |
# | join_point_name | String | False | Name of the referenced active directory join point, alternative to `join_point_id` |
#
# YAML: ise.identity_management.active_directory_join_domain_with_all_nodes (list, objects identified by join_point_name)
#

locals {
  # Defaults for active directory join domain with all nodes (module defaults merged with user defaults)
  defaults_active_directory_join_domain_with_all_nodes = try(local.defaults.ise.identity_management.active_directory_join_domain_with_all_nodes, {})

  # Active directory join domain with all nodes objects with defaults
  active_directory_join_domain_with_all_nodes = [for item in try(local.ise.identity_management.active_directory_join_domain_with_all_nodes, []) : merge(
    # defaults of nested lists apply to each list item
    { for k, v in local.defaults_active_directory_join_domain_with_all_nodes : k => v if !contains(["additional_data"], k) },
    item,
    { for k in ["additional_data"] : k => [for i in item[k] : merge(try(local.defaults_active_directory_join_domain_with_all_nodes[k], {}), i)] if try(item[k], null) != null }
  )]
}

resource "ise_active_directory_join_domain_with_all_nodes" "active_directory_join_domain_with_all_nodes" {
  for_each = { for item in local.active_directory_join_domain_with_all_nodes : try(item.join_point_name, item.join_point_id, "") => item }

  join_point_id = try(each.value.join_point_id, null) != null ? each.value.join_point_id : try(each.value.join_point_name, null) != null ? lookup(local.active_directory_join_point_ids, each.value.join_point_name, null) : null
  additional_data = try(each.value.additional_data, null) == null ? null : [for i1 in each.value.additional_data : {
    name  = try(i1.name, null)
    value = try(i1.value, null)
  }]
}

#
# ==================================================================
# ACTIVE DIRECTORY JOIN POINT
# ==================================================================
#
# | Attribute Name | Type | Required | Description |
# |--------------|------|----------|-------------|
# | name | String | True | The name of the active directory join point |
# | description | String | False | Join point description |
# | domain | String | True | AD domain associated with the join point |
# | ad_scopes_names | String | False | String that contains the names of the scopes that the active directory belongs to. Names are separated by comma. |
# | enable_domain_allowed_list | Bool | False |  |
# | groups | List | False | List of AD Groups |
# | attributes | List | False | List of AD attributes |
# | rewrite_rules | List | False | List of Rewrite rules |
# | enable_rewrites | Bool | False | Enable Rewrites |
# | enable_pass_change | Bool | False | Enable Password Change |
# | enable_machine_auth | Bool | False | Enable Machine Authentication |
# | enable_machine_access | Bool | False | Enable Machine Access |
# | enable_dialin_permission_check | Bool | False | Enable Dial In Permission Check |
# | plaintext_auth | Bool | False | Plain Text Authentication |
# | aging_time | Int64 | False | Aging Time |
# | enable_callback_for_dialin_client | Bool | False | Enable Callback For Dial In Client |
# | identity_not_in_ad_behaviour | String | False | Identity Not In AD Behaviour |
# | unreachable_domains_behaviour | String | False | Unreachable Domains Behaviour |
# | schema | String | False | Schema |
# | first_name | String | False | User info attribute |
# | department | String | False | User info attribute |
# | last_name | String | False | User info attribute |
# | organizational_unit | String | False | User info attribute |
# | job_title | String | False | User info attribute |
# | locality | String | False | User info attribute |
# | email | String | False | User info attribute |
# | state_or_province | String | False | User info attribute |
# | telephone | String | False | User info attribute |
# | country | String | False | User info attribute |
# | street_address | String | False | User info attribute |
# | enable_failed_auth_protection | Bool | False | Enable prevent AD account lockout due to too many bad password attempts |
# | failed_auth_threshold | Int64 | False | Number of bad password attempts |
# | auth_protection_type | String | False | Enable prevent AD account lockout for WIRELESS/WIRED/BOTH |
#
# YAML: ise.identity_management.active_directory_join_point (list, objects identified by name)
#

locals {
  # Defaults for active directory join point (module defaults merged with user defaults)
  defaults_active_directory_join_point = try(local.defaults.ise.identity_management.active_directory_join_point, {})

  # Active directory join point objects with defaults
  active_directory_join_point = [for item in try(local.ise.identity_management.active_directory_join_point, []) : merge(
    # defaults of nested lists apply to each list item
    { for k, v in local.defaults_active_directory_join_point : k => v if !contains(["groups", "attributes", "rewrite_rules"], k) },
    item,
    { for k in ["groups", "attributes", "rewrite_rules"] : k => [for i in item[k] : merge(try(local.defaults_active_directory_join_point[k], {}), i)] if try(item[k], null) != null }
  )]
}

resource "ise_active_directory_join_point" "active_directory_join_point" {
  for_each = { for item in local.active_directory_join_point : item.name => item }

  name                       = try(each.value.name, null)
  description                = try(each.value.description, null)
  domain                     = try(each.value.domain, null)
  ad_scopes_names            = try(each.value.ad_scopes_names, null)
  enable_domain_allowed_list = try(each.value.enable_domain_allowed_list, null)
  groups = try(each.value.groups, null) == null ? null : [for i1 in each.value.groups : {
    name = try(i1.name, null)
    sid  = try(i1.sid, null)
    type = try(i1.type, null)
  }]
  attributes = try(each.value.attributes, null) == null ? null : [for i1 in each.value.attributes : {
    name          = try(i1.name, null)
    type          = try(i1.type, null)
    internal_name = try(i1.internal_name, null)
    default_value = try(i1.default_value, null)
  }]
  rewrite_rules = try(each.value.rewrite_rules, null) == null ? null : [for i1 in each.value.rewrite_rules : {
    row_id         = try(i1.row_id, null)
    rewrite_match  = try(i1.rewrite_match, null)
    rewrite_result = try(i1.rewrite_result, null)
  }]
  enable_rewrites                   = try(each.value.enable_rewrites, null)
  enable_pass_change                = try(each.value.enable_pass_change, null)
  enable_machine_auth               = try(each.value.enable_machine_auth, null)
  enable_machine_access             = try(each.value.enable_machine_access, null)
  enable_dialin_permission_check    = try(each.value.enable_dialin_permission_check, null)
  plaintext_auth                    = try(each.value.plaintext_auth, null)
  aging_time                        = try(each.value.aging_time, null)
  enable_callback_for_dialin_client = try(each.value.enable_callback_for_dialin_client, null)
  identity_not_in_ad_behaviour      = try(each.value.identity_not_in_ad_behaviour, null)
  unreachable_domains_behaviour     = try(each.value.unreachable_domains_behaviour, null)
  schema                            = try(each.value.schema, null)
  first_name                        = try(each.value.first_name, null)
  department                        = try(each.value.department, null)
  last_name                         = try(each.value.last_name, null)
  organizational_unit               = try(each.value.organizational_unit, null)
  job_title                         = try(each.value.job_title, null)
  locality                          = try(each.value.locality, null)
  email                             = try(each.value.email, null)
  state_or_province                 = try(each.value.state_or_province, null)
  telephone                         = try(each.value.telephone, null)
  country                           = try(each.value.country, null)
  street_address                    = try(each.value.street_address, null)
  enable_failed_auth_protection     = try(each.value.enable_failed_auth_protection, null)
  failed_auth_threshold             = try(each.value.failed_auth_threshold, null)
  auth_protection_type              = try(each.value.auth_protection_type, null)

  lifecycle {
    ignore_changes = [aging_time]
  }
}


#
# ------------------------------------------------------------------
# ACTIVE DIRECTORY JOIN POINT REFERENCES
# ------------------------------------------------------------------
#
# Other objects can refer to active directory join point objects by name. Names are
# resolved to IDs of objects managed by this module.
#

locals {
  active_directory_join_point_referenced_names = distinct(compact(flatten([
    [for item in local.active_directory_add_groups : [for v0 in [item] : try(v0.name, null) if try(v0.join_point_id, null) == null]],
    [for item in local.active_directory_join_domain_with_all_nodes : [for v0 in [item] : try(v0.join_point_name, null) if try(v0.join_point_id, null) == null]],
  ])))
  active_directory_join_point_managed_names   = [for item in local.active_directory_join_point : item.name]
  active_directory_join_point_unmanaged_names = [for n in local.active_directory_join_point_referenced_names : n if !contains(local.active_directory_join_point_managed_names, n)]
}

# The provider cannot look up active directory join point objects by name
resource "terraform_data" "active_directory_join_point_references" {
  lifecycle {
    precondition {
      condition     = length(local.active_directory_join_point_unmanaged_names) == 0
      error_message = "Active directory join point objects not managed by this module must be referred to by ID, not by name: ${join(", ", local.active_directory_join_point_unmanaged_names)}"
    }
  }
}

locals {
  active_directory_join_point_lookup_ids = {}
  active_directory_join_point_ids = merge(
    local.active_directory_join_point_lookup_ids,
    { for k, v in ise_active_directory_join_point.active_directory_join_point : k => v.id },
  )
}

#
# ==================================================================
# CERTIFICATE AUTHENTICATION PROFILE
# ==================================================================
#
# | Attribute Name | Type | Required | Description |
# |--------------|------|----------|-------------|
# | name | String | True | The name of the certificate profile |
# | description | String | False | Description |
# | allowed_as_user_name | Bool | False | Allow as username |
# | external_identity_store_name | String | False | Referred IDStore name for the Certificate Profile or `[not applicable]` in case no identity store is chosen |
# | certificate_attribute_name | String | False | Attribute name of the Certificate Profile - used only when CERTIFICATE is chosen in `username_from`. When `username_from` is set to UPN, ISE automatically sets this to ALL_SUBJECT_AND_ALTERNATIVE_NAMES. |
# | match_mode | String | False | Match mode of the Certificate Profile. Allowed values: NEVER, RESOLVE_IDENTITY_AMBIGUITY, BINARY_COMPARISON |
# | username_from | String | False | The attribute in the certificate where the user name should be taken from. Allowed values: `CERTIFICATE` (for a specific attribute as defined in certificateAttributeName), `UPN` (for using any Subject or Alternative Name Attributes in the Certificate - an option only in AD) |
#
# YAML: ise.identity_management.certificate_authentication_profile (list, objects identified by name)
#

locals {
  # Defaults for certificate authentication profile (module defaults merged with user defaults)
  defaults_certificate_authentication_profile = try(local.defaults.ise.identity_management.certificate_authentication_profile, {})

  # Certificate authentication profile objects with defaults
  certificate_authentication_profile = [for item in try(local.ise.identity_management.certificate_authentication_profile, []) : merge(
    local.defaults_certificate_authentication_profile,
    item
  )]
}

resource "ise_certificate_authentication_profile" "certificate_authentication_profile" {
  for_each = { for item in local.certificate_authentication_profile : item.name => item }

  name                         = try(each.value.name, null)
  description                  = try(each.value.description, null)
  allowed_as_user_name         = try(each.value.allowed_as_user_name, null)
  external_identity_store_name = try(each.value.external_identity_store_name, null)
  certificate_attribute_name   = try(each.value.certificate_attribute_name, null)
  match_mode                   = try(each.value.match_mode, null)
  username_from                = try(each.value.username_from, null)
}

#
# ==================================================================
# ENDPOINT
# ==================================================================
#
# | Attribute Name | Type | Required | Description |
# |--------------|------|----------|-------------|
# | name | String | True | The name of the endpoint |
# | description | String | False | Description |
# | mac | String | True | MAC address of the endpoint |
# | group_id | String | False | Identity Group ID |
# | profile_id | String | False | Profile ID |
# | static_profile_assignment | Bool | True | Static Profile Assignment |
# | static_profile_assignment_defined | Bool | False | Static Profile Assignment Defined |
# | static_group_assignment | Bool | True | Static Group Assignment |
# | static_group_assignment_defined | Bool | False | staticGroupAssignmentDefined |
# | custom_attributes | Map | False | Custom Attributes |
# | identity_store | String | False | Identity Store |
# | identity_store_id | String | False | Identity Store Id |
# | portal_user | String | False | Portal User |
# | mdm_server_name | String | False | Mdm Server Name |
# | mdm_reachable | Bool | False | Mdm Reachable |
# | mdm_enrolled | Bool | False | Mdm Enrolled |
# | mdm_compliance_status | Bool | False | Mdm Compliance Status |
# | mdm_os | String | False | Mdm OS |
# | mdm_manufacturer | String | False | Mdm Manufacturer |
# | mdm_model | String | False | Mdm Model |
# | mdm_serial | String | False | Mdm Serial |
# | mdm_encrypted | Bool | False | Mdm Encrypted |
# | mdm_pinlock | Bool | False | Mdm Pinlock |
# | mdm_jail_broken | Bool | False | Mdm JailBroken |
# | mdm_imei | String | False | Mdm IMEI |
# | mdm_phone_number | String | False | Mdm PhoneNumber |
# | group_name | String | False | Name of the referenced endpoint identity group, alternative to `group_id` |
# | profile_name | String | False | Name of the referenced profiler profile, alternative to `profile_id` |
#
# YAML: ise.identity_management.endpoint (list, objects identified by name)
#

locals {
  # Defaults for endpoint (module defaults merged with user defaults)
  defaults_endpoint = try(local.defaults.ise.identity_management.endpoint, {})

  # Endpoint objects with defaults
  endpoint = [for item in try(local.ise.identity_management.endpoint, []) : merge(
    local.defaults_endpoint,
    item
  )]
}

resource "ise_endpoint" "endpoint" {
  for_each = { for item in local.endpoint : item.name => item }

  name                              = try(each.value.name, null)
  description                       = try(each.value.description, null)
  mac                               = try(each.value.mac, null)
  group_id                          = try(each.value.group_id, null) != null ? each.value.group_id : try(each.value.group_name, null) != null ? local.endpoint_identity_group_ids[each.value.group_name] : null
  profile_id                        = try(each.value.profile_id, null) != null ? each.value.profile_id : try(each.value.profile_name, null) != null ? local.profiler_profile_ids[each.value.profile_name] : null
  static_profile_assignment         = try(each.value.static_profile_assignment, null)
  static_profile_assignment_defined = try(each.value.static_profile_assignment_defined, null)
  static_group_assignment           = try(each.value.static_group_assignment, null)
  static_group_assignment_defined   = try(each.value.static_group_assignment_defined, null)
  custom_attributes                 = try(each.value.custom_attributes, null)
  identity_store                    = try(each.value.identity_store, null)
  identity_store_id                 = try(each.value.identity_store_id, null)
  portal_user                       = try(each.value.portal_user, null)
  mdm_server_name                   = try(each.value.mdm_server_name, null)
  mdm_reachable                     = try(each.value.mdm_reachable, null)
  mdm_enrolled                      = try(each.value.mdm_enrolled, null)
  mdm_compliance_status             = try(each.value.mdm_compliance_status, null)
  mdm_os                            = try(each.value.mdm_os, null)
  mdm_manufacturer                  = try(each.value.mdm_manufacturer, null)
  mdm_model                         = try(each.value.mdm_model, null)
  mdm_serial                        = try(each.value.mdm_serial, null)
  mdm_encrypted                     = try(each.value.mdm_encrypted, null)
  mdm_pinlock                       = try(each.value.mdm_pinlock, null)
  mdm_jail_broken                   = try(each.value.mdm_jail_broken, null)
  mdm_imei                          = try(each.value.mdm_imei, null)
  mdm_phone_number                  = try(each.value.mdm_phone_number, null)
}

#
# ==================================================================
# ENDPOINT CUSTOM ATTRIBUTE
# ==================================================================
#
# | Attribute Name | Type | Required | Description |
# |--------------|------|----------|-------------|
# | attribute_name | String | True | The name of the attribute |
# | attribute_type | String | True | Attribute type |
#
# YAML: ise.identity_management.endpoint_custom_attribute (list, objects identified by attribute_name)
#

locals {
  # Defaults for endpoint custom attribute (module defaults merged with user defaults)
  defaults_endpoint_custom_attribute = try(local.defaults.ise.identity_management.endpoint_custom_attribute, {})

  # Endpoint custom attribute objects with defaults
  endpoint_custom_attribute = [for item in try(local.ise.identity_management.endpoint_custom_attribute, []) : merge(
    local.defaults_endpoint_custom_attribute,
    item
  )]
}

resource "ise_endpoint_custom_attribute" "endpoint_custom_attribute" {
  for_each = { for item in local.endpoint_custom_attribute : item.attribute_name => item }

  attribute_name = try(each.value.attribute_name, null)
  attribute_type = try(each.value.attribute_type, null)
}

#
# ==================================================================
# ENDPOINT IDENTITY GROUP
# ==================================================================
#
# | Attribute Name | Type | Required | Description |
# |--------------|------|----------|-------------|
# | name | String | True | The name of the endpoint identity group |
# | description | String | False | Description |
# | system_defined | Bool | False | System defined endpoint identity group |
# | parent_endpoint_identity_group_id | String | False | Parent endpoint identity group ID |
# | parent_endpoint_identity_group_name | String | False | Name of the referenced endpoint identity group, alternative to `parent_endpoint_identity_group_id` |
#
# YAML: ise.identity_management.endpoint_identity_group (list, objects identified by name)
#

locals {
  # Defaults for endpoint identity group (module defaults merged with user defaults)
  defaults_endpoint_identity_group = try(local.defaults.ise.identity_management.endpoint_identity_group, {})

  # Endpoint identity group objects with defaults
  endpoint_identity_group = [for item in try(local.ise.identity_management.endpoint_identity_group, []) : merge(
    local.defaults_endpoint_identity_group,
    item
  )]
}

locals {
  # Managed endpoint identity group objects each object refers to. Objects are
  # created in tiers so that referenced objects exist before the objects using them.
  endpoint_identity_group_self_references = {
    for item in local.endpoint_identity_group : item.name => [
      for n in distinct(compact(flatten([
        [for v0 in [item] : try(v0.parent_endpoint_identity_group_name, null) if try(v0.parent_endpoint_identity_group_id, null) == null],
      ]))) : n if contains([for i in local.endpoint_identity_group : i.name], n)
    ]
  }
  endpoint_identity_group_tier0    = [for k, refs in local.endpoint_identity_group_self_references : k if length(refs) == 0]
  endpoint_identity_group_tier1    = [for k, refs in local.endpoint_identity_group_self_references : k if !contains(concat(local.endpoint_identity_group_tier0), k) && alltrue([for n in refs : contains(concat(local.endpoint_identity_group_tier0), n)])]
  endpoint_identity_group_tier2    = [for k, refs in local.endpoint_identity_group_self_references : k if !contains(concat(local.endpoint_identity_group_tier0, local.endpoint_identity_group_tier1), k) && alltrue([for n in refs : contains(concat(local.endpoint_identity_group_tier0, local.endpoint_identity_group_tier1), n)])]
  endpoint_identity_group_tier3    = [for k, refs in local.endpoint_identity_group_self_references : k if !contains(concat(local.endpoint_identity_group_tier0, local.endpoint_identity_group_tier1, local.endpoint_identity_group_tier2), k) && alltrue([for n in refs : contains(concat(local.endpoint_identity_group_tier0, local.endpoint_identity_group_tier1, local.endpoint_identity_group_tier2), n)])]
  endpoint_identity_group_untiered = [for k in keys(local.endpoint_identity_group_self_references) : k if !contains(concat(local.endpoint_identity_group_tier0, local.endpoint_identity_group_tier1, local.endpoint_identity_group_tier2, local.endpoint_identity_group_tier3), k)]
}

resource "terraform_data" "endpoint_identity_group_tiers" {
  lifecycle {
    precondition {
      condition     = length(local.endpoint_identity_group_untiered) == 0
      error_message = "Endpoint identity group objects refer to each other in a loop or more than 3 levels deep: ${join(", ", local.endpoint_identity_group_untiered)}"
    }
  }
}

resource "ise_endpoint_identity_group" "endpoint_identity_group" {
  for_each = { for item in local.endpoint_identity_group : item.name => item if contains(local.endpoint_identity_group_tier0, item.name) }

  name                              = try(each.value.name, null)
  description                       = try(each.value.description, null)
  system_defined                    = try(each.value.system_defined, null)
  parent_endpoint_identity_group_id = try(each.value.parent_endpoint_identity_group_id, null) != null ? each.value.parent_endpoint_identity_group_id : try(each.value.parent_endpoint_identity_group_name, null) != null ? local.endpoint_identity_group_ids_tier0[each.value.parent_endpoint_identity_group_name] : null
}

resource "ise_endpoint_identity_group" "endpoint_identity_group_tier1" {
  for_each = { for item in local.endpoint_identity_group : item.name => item if contains(local.endpoint_identity_group_tier1, item.name) }

  name                              = try(each.value.name, null)
  description                       = try(each.value.description, null)
  system_defined                    = try(each.value.system_defined, null)
  parent_endpoint_identity_group_id = try(each.value.parent_endpoint_identity_group_id, null) != null ? each.value.parent_endpoint_identity_group_id : try(each.value.parent_endpoint_identity_group_name, null) != null ? local.endpoint_identity_group_ids_tier1[each.value.parent_endpoint_identity_group_name] : null
}

resource "ise_endpoint_identity_group" "endpoint_identity_group_tier2" {
  for_each = { for item in local.endpoint_identity_group : item.name => item if contains(local.endpoint_identity_group_tier2, item.name) }

  name                              = try(each.value.name, null)
  description                       = try(each.value.description, null)
  system_defined                    = try(each.value.system_defined, null)
  parent_endpoint_identity_group_id = try(each.value.parent_endpoint_identity_group_id, null) != null ? each.value.parent_endpoint_identity_group_id : try(each.value.parent_endpoint_identity_group_name, null) != null ? local.endpoint_identity_group_ids_tier2[each.value.parent_endpoint_identity_group_name] : null
}

resource "ise_endpoint_identity_group" "endpoint_identity_group_tier3" {
  for_each = { for item in local.endpoint_identity_group : item.name => item if contains(local.endpoint_identity_group_tier3, item.name) }

  name                              = try(each.value.name, null)
  description                       = try(each.value.description, null)
  system_defined                    = try(each.value.system_defined, null)
  parent_endpoint_identity_group_id = try(each.value.parent_endpoint_identity_group_id, null) != null ? each.value.parent_endpoint_identity_group_id : try(each.value.parent_endpoint_identity_group_name, null) != null ? local.endpoint_identity_group_ids_tier3[each.value.parent_endpoint_identity_group_name] : null
}


#
# ------------------------------------------------------------------
# ENDPOINT IDENTITY GROUP REFERENCES
# ------------------------------------------------------------------
#
# Other objects can refer to endpoint identity group objects by name. Names are
# resolved to IDs of objects managed by this module, or looked up in ISE.
#

locals {
  endpoint_identity_group_referenced_names = distinct(compact(flatten([
    [for item in local.endpoint : [for v0 in [item] : try(v0.group_name, null) if try(v0.group_id, null) == null]],
    [for item in local.endpoint_identity_group : [for v0 in [item] : try(v0.parent_endpoint_identity_group_name, null) if try(v0.parent_endpoint_identity_group_id, null) == null]],
  ])))
  endpoint_identity_group_managed_names   = [for item in local.endpoint_identity_group : item.name]
  endpoint_identity_group_unmanaged_names = [for n in local.endpoint_identity_group_referenced_names : n if !contains(local.endpoint_identity_group_managed_names, n)]
}

data "ise_endpoint_identity_group" "endpoint_identity_group" {
  for_each = toset(local.endpoint_identity_group_unmanaged_names)

  name = each.key
}

locals {
  endpoint_identity_group_lookup_ids = { for k, v in data.ise_endpoint_identity_group.endpoint_identity_group : k => v.id }
  endpoint_identity_group_ids_tier0 = merge(
    local.endpoint_identity_group_lookup_ids,
  )
  endpoint_identity_group_ids_tier1 = merge(
    local.endpoint_identity_group_lookup_ids,
    { for k, v in ise_endpoint_identity_group.endpoint_identity_group : k => v.id },
  )
  endpoint_identity_group_ids_tier2 = merge(
    local.endpoint_identity_group_lookup_ids,
    { for k, v in ise_endpoint_identity_group.endpoint_identity_group : k => v.id },
    { for k, v in ise_endpoint_identity_group.endpoint_identity_group_tier1 : k => v.id },
  )
  endpoint_identity_group_ids_tier3 = merge(
    local.endpoint_identity_group_lookup_ids,
    { for k, v in ise_endpoint_identity_group.endpoint_identity_group : k => v.id },
    { for k, v in ise_endpoint_identity_group.endpoint_identity_group_tier1 : k => v.id },
    { for k, v in ise_endpoint_identity_group.endpoint_identity_group_tier2 : k => v.id },
  )
  endpoint_identity_group_ids = merge(
    local.endpoint_identity_group_lookup_ids,
    { for k, v in ise_endpoint_identity_group.endpoint_identity_group : k => v.id },
    { for k, v in ise_endpoint_identity_group.endpoint_identity_group_tier1 : k => v.id },
    { for k, v in ise_endpoint_identity_group.endpoint_identity_group_tier2 : k => v.id },
    { for k, v in ise_endpoint_identity_group.endpoint_identity_group_tier3 : k => v.id },
  )
}

#
# ==================================================================
# IDENTITY SOURCE SEQUENCE
# ==================================================================
#
# | Attribute Name | Type | Required | Description |
# |--------------|------|----------|-------------|
# | name | String | True | The name of the identity source sequence |
# | description | String | False | Description |
# | break_on_store_fail | Bool | True | Do not access other stores in the sequence if a selected identity store cannot be accessed for authentication |
# | certificate_authentication_profile | String | False | Certificate Authentication Profile, empty if doesn't exist |
# | identity_sources | List | True |  |
#
# YAML: ise.identity_management.identity_source_sequence (list, objects identified by name)
#

locals {
  # Defaults for identity source sequence (module defaults merged with user defaults)
  defaults_identity_source_sequence = try(local.defaults.ise.identity_management.identity_source_sequence, {})

  # Identity source sequence objects with defaults
  identity_source_sequence = [for item in try(local.ise.identity_management.identity_source_sequence, []) : merge(
    # defaults of nested lists apply to each list item
    { for k, v in local.defaults_identity_source_sequence : k => v if !contains(["identity_sources"], k) },
    item,
    { for k in ["identity_sources"] : k => [for i in item[k] : merge(try(local.defaults_identity_source_sequence[k], {}), i)] if try(item[k], null) != null }
  )]
}

resource "ise_identity_source_sequence" "identity_source_sequence" {
  for_each = { for item in local.identity_source_sequence : item.name => item }

  name                               = try(each.value.name, null)
  description                        = try(each.value.description, null)
  break_on_store_fail                = try(each.value.break_on_store_fail, null)
  certificate_authentication_profile = try(each.value.certificate_authentication_profile, null)
  identity_sources = try(each.value.identity_sources, null) == null ? null : [for i1 in each.value.identity_sources : {
    name  = try(i1.name, null)
    order = try(i1.order, null)
  }]
}

#
# ==================================================================
# INTERNAL USER
# ==================================================================
#
# | Attribute Name | Type | Required | Description |
# |--------------|------|----------|-------------|
# | name | String | True | The name of the internal user |
# | password | String | False | The password of the internal user. Required when creating a new user. When managing existing (brownfield) users the password can be omitted and the existing password will be preserved. |
# | change_password | Bool | False | Requires the user to change the password |
# | email | String | False | Email address |
# | account_name_alias | String | False | The Account Name Alias will be used to send email notifications about password expiration. This field is only supported from ISE 3.2. |
# | enable_password | String | False | This field is added in ISE 2.0 to support TACACS+ |
# | enabled | Bool | False | Whether the user is enabled/disabled |
# | password_never_expires | Bool | False | Set to `true` to indicate the user password never expires. This will not apply to Users who are also ISE Admins. This field is only supported from ISE 3.2. |
# | first_name | String | False | First name of the internal user |
# | last_name | String | False | Last name of the internal user |
# | identity_groups | String | False | Comma separated list of identity group IDs. |
# | custom_attributes | Map | False | Key value map of custom attributes. The keys must be defined in the ISE identity store configuration. |
# | password_id_store | String | False | The ID store where the internal user's password is kept |
# | description | String | False | Description |
# | identity_group_names | List | False | Names of the referenced user identity group, alternative to `identity_groups` |
#
# YAML: ise.identity_management.internal_user (list, objects identified by name)
#

locals {
  # Defaults for internal user (module defaults merged with user defaults)
  defaults_internal_user = try(local.defaults.ise.identity_management.internal_user, {})

  # Internal user objects with defaults
  internal_user = [for item in try(local.ise.identity_management.internal_user, []) : merge(
    local.defaults_internal_user,
    item
  )]
}

resource "ise_internal_user" "internal_user" {
  for_each = { for item in local.internal_user : item.name => item }

  name                   = try(each.value.name, null)
  password               = sensitive(try(each.value.password, null))
  change_password        = sensitive(try(each.value.change_password, null))
  email                  = try(each.value.email, null)
  account_name_alias     = try(each.value.account_name_alias, null)
  enable_password        = sensitive(try(each.value.enable_password, null))
  enabled                = try(each.value.enabled, null)
  password_never_expires = try(each.value.password_never_expires, null)
  first_name             = try(each.value.first_name, null)
  last_name              = try(each.value.last_name, null)
  identity_groups        = try(each.value.identity_groups, null) != null ? each.value.identity_groups : try(each.value.identity_group_names, null) != null ? join(",", sort([for n in each.value.identity_group_names : local.user_identity_group_ids[n]])) : null
  custom_attributes      = try(each.value.custom_attributes, null)
  password_id_store      = try(each.value.password_id_store, null)
  description            = try(each.value.description, null)
}

#
# ==================================================================
# USER IDENTITY GROUP
# ==================================================================
#
# | Attribute Name | Type | Required | Description |
# |--------------|------|----------|-------------|
# | name | String | True | The name of the user identity group |
# | description | String | False | Description |
# | parent | String | False | Parent user identity group, e.g. `NAC Group:NAC:IdentityGroups:User Identity Groups` |
#
# YAML: ise.identity_management.user_identity_group (list, objects identified by name)
#

locals {
  # Defaults for user identity group (module defaults merged with user defaults)
  defaults_user_identity_group = try(local.defaults.ise.identity_management.user_identity_group, {})

  # User identity group objects with defaults
  user_identity_group = [for item in try(local.ise.identity_management.user_identity_group, []) : merge(
    local.defaults_user_identity_group,
    item
  )]
}

resource "ise_user_identity_group" "user_identity_group" {
  for_each = { for item in local.user_identity_group : item.name => item }

  name        = try(each.value.name, null)
  description = try(each.value.description, null)
  parent      = try(each.value.parent, null)
}


#
# ------------------------------------------------------------------
# USER IDENTITY GROUP REFERENCES
# ------------------------------------------------------------------
#
# Other objects can refer to user identity group objects by name. Names are
# resolved to IDs of objects managed by this module, or looked up in ISE.
#

locals {
  user_identity_group_referenced_names = distinct(compact(flatten([
    [for item in local.internal_user : [for v0 in [item] : try(v0.identity_group_names, []) if try(v0.identity_groups, null) == null]],
  ])))
  user_identity_group_managed_names   = [for item in local.user_identity_group : item.name]
  user_identity_group_unmanaged_names = [for n in local.user_identity_group_referenced_names : n if !contains(local.user_identity_group_managed_names, n)]
}

data "ise_user_identity_group" "user_identity_group" {
  for_each = toset(local.user_identity_group_unmanaged_names)

  name = each.key
}

locals {
  user_identity_group_lookup_ids = { for k, v in data.ise_user_identity_group.user_identity_group : k => v.id }
  user_identity_group_ids = merge(
    local.user_identity_group_lookup_ids,
    { for k, v in ise_user_identity_group.user_identity_group : k => v.id },
  )
}


#
# ------------------------------------------------------------------
# PROFILER PROFILE REFERENCES
# ------------------------------------------------------------------
#
# Other objects can refer to profiler profile objects by name. Names are
# resolved to IDs of objects managed by this module, or looked up in ISE.
#

locals {
  profiler_profile_referenced_names = distinct(compact(flatten([
    [for item in local.endpoint : [for v0 in [item] : try(v0.profile_name, null) if try(v0.profile_id, null) == null]],
    [for item in local.network_access_authentication_rule : [for v0 in [item] : try(v0.condition_attribute_value, null) if !can(regex(local.id_regexp, v0.condition_attribute_value)) && try(v0.condition_attribute_name, null) == "EndPointPolicy"]],
    [for item in local.network_access_authentication_rule : [for v1 in try(item.children, []) : try(v1.attribute_value, null) if !can(regex(local.id_regexp, v1.attribute_value)) && try(v1.attribute_name, null) == "EndPointPolicy"]],
    [for item in local.network_access_authentication_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : try(v2.attribute_value, null) if !can(regex(local.id_regexp, v2.attribute_value)) && try(v2.attribute_name, null) == "EndPointPolicy"]]],
    [for item in local.network_access_authentication_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : try(v3.attribute_value, null) if !can(regex(local.id_regexp, v3.attribute_value)) && try(v3.attribute_name, null) == "EndPointPolicy"]]]],
    [for item in local.network_access_authentication_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : try(v4.attribute_value, null) if !can(regex(local.id_regexp, v4.attribute_value)) && try(v4.attribute_name, null) == "EndPointPolicy"]]]]],
    [for item in local.network_access_authentication_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : [for v5 in try(v4.children, []) : try(v5.attribute_value, null) if !can(regex(local.id_regexp, v5.attribute_value)) && try(v5.attribute_name, null) == "EndPointPolicy"]]]]]],
    [for item in local.network_access_authentication_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : [for v5 in try(v4.children, []) : [for v6 in try(v5.children, []) : try(v6.attribute_value, null) if !can(regex(local.id_regexp, v6.attribute_value)) && try(v6.attribute_name, null) == "EndPointPolicy"]]]]]]],
    [for item in local.network_access_authorization_exception_rule : [for v0 in [item] : try(v0.condition_attribute_value, null) if !can(regex(local.id_regexp, v0.condition_attribute_value)) && try(v0.condition_attribute_name, null) == "EndPointPolicy"]],
    [for item in local.network_access_authorization_exception_rule : [for v1 in try(item.children, []) : try(v1.attribute_value, null) if !can(regex(local.id_regexp, v1.attribute_value)) && try(v1.attribute_name, null) == "EndPointPolicy"]],
    [for item in local.network_access_authorization_exception_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : try(v2.attribute_value, null) if !can(regex(local.id_regexp, v2.attribute_value)) && try(v2.attribute_name, null) == "EndPointPolicy"]]],
    [for item in local.network_access_authorization_exception_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : try(v3.attribute_value, null) if !can(regex(local.id_regexp, v3.attribute_value)) && try(v3.attribute_name, null) == "EndPointPolicy"]]]],
    [for item in local.network_access_authorization_exception_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : try(v4.attribute_value, null) if !can(regex(local.id_regexp, v4.attribute_value)) && try(v4.attribute_name, null) == "EndPointPolicy"]]]]],
    [for item in local.network_access_authorization_exception_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : [for v5 in try(v4.children, []) : try(v5.attribute_value, null) if !can(regex(local.id_regexp, v5.attribute_value)) && try(v5.attribute_name, null) == "EndPointPolicy"]]]]]],
    [for item in local.network_access_authorization_exception_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : [for v5 in try(v4.children, []) : [for v6 in try(v5.children, []) : try(v6.attribute_value, null) if !can(regex(local.id_regexp, v6.attribute_value)) && try(v6.attribute_name, null) == "EndPointPolicy"]]]]]]],
    [for item in local.network_access_authorization_global_exception_rule : [for v0 in [item] : try(v0.condition_attribute_value, null) if !can(regex(local.id_regexp, v0.condition_attribute_value)) && try(v0.condition_attribute_name, null) == "EndPointPolicy"]],
    [for item in local.network_access_authorization_global_exception_rule : [for v1 in try(item.children, []) : try(v1.attribute_value, null) if !can(regex(local.id_regexp, v1.attribute_value)) && try(v1.attribute_name, null) == "EndPointPolicy"]],
    [for item in local.network_access_authorization_global_exception_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : try(v2.attribute_value, null) if !can(regex(local.id_regexp, v2.attribute_value)) && try(v2.attribute_name, null) == "EndPointPolicy"]]],
    [for item in local.network_access_authorization_global_exception_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : try(v3.attribute_value, null) if !can(regex(local.id_regexp, v3.attribute_value)) && try(v3.attribute_name, null) == "EndPointPolicy"]]]],
    [for item in local.network_access_authorization_global_exception_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : try(v4.attribute_value, null) if !can(regex(local.id_regexp, v4.attribute_value)) && try(v4.attribute_name, null) == "EndPointPolicy"]]]]],
    [for item in local.network_access_authorization_global_exception_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : [for v5 in try(v4.children, []) : try(v5.attribute_value, null) if !can(regex(local.id_regexp, v5.attribute_value)) && try(v5.attribute_name, null) == "EndPointPolicy"]]]]]],
    [for item in local.network_access_authorization_global_exception_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : [for v5 in try(v4.children, []) : [for v6 in try(v5.children, []) : try(v6.attribute_value, null) if !can(regex(local.id_regexp, v6.attribute_value)) && try(v6.attribute_name, null) == "EndPointPolicy"]]]]]]],
    [for item in local.network_access_authorization_rule : [for v0 in [item] : try(v0.condition_attribute_value, null) if !can(regex(local.id_regexp, v0.condition_attribute_value)) && try(v0.condition_attribute_name, null) == "EndPointPolicy"]],
    [for item in local.network_access_authorization_rule : [for v1 in try(item.children, []) : try(v1.attribute_value, null) if !can(regex(local.id_regexp, v1.attribute_value)) && try(v1.attribute_name, null) == "EndPointPolicy"]],
    [for item in local.network_access_authorization_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : try(v2.attribute_value, null) if !can(regex(local.id_regexp, v2.attribute_value)) && try(v2.attribute_name, null) == "EndPointPolicy"]]],
    [for item in local.network_access_authorization_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : try(v3.attribute_value, null) if !can(regex(local.id_regexp, v3.attribute_value)) && try(v3.attribute_name, null) == "EndPointPolicy"]]]],
    [for item in local.network_access_authorization_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : try(v4.attribute_value, null) if !can(regex(local.id_regexp, v4.attribute_value)) && try(v4.attribute_name, null) == "EndPointPolicy"]]]]],
    [for item in local.network_access_authorization_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : [for v5 in try(v4.children, []) : try(v5.attribute_value, null) if !can(regex(local.id_regexp, v5.attribute_value)) && try(v5.attribute_name, null) == "EndPointPolicy"]]]]]],
    [for item in local.network_access_authorization_rule : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : [for v5 in try(v4.children, []) : [for v6 in try(v5.children, []) : try(v6.attribute_value, null) if !can(regex(local.id_regexp, v6.attribute_value)) && try(v6.attribute_name, null) == "EndPointPolicy"]]]]]]],
    [for item in local.network_access_condition : [for v0 in [item] : try(v0.attribute_value, null) if !can(regex(local.id_regexp, v0.attribute_value)) && try(v0.attribute_name, null) == "EndPointPolicy"]],
    [for item in local.network_access_condition : [for v1 in try(item.children, []) : try(v1.attribute_value, null) if !can(regex(local.id_regexp, v1.attribute_value)) && try(v1.attribute_name, null) == "EndPointPolicy"]],
    [for item in local.network_access_condition : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : try(v2.attribute_value, null) if !can(regex(local.id_regexp, v2.attribute_value)) && try(v2.attribute_name, null) == "EndPointPolicy"]]],
    [for item in local.network_access_condition : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : try(v3.attribute_value, null) if !can(regex(local.id_regexp, v3.attribute_value)) && try(v3.attribute_name, null) == "EndPointPolicy"]]]],
    [for item in local.network_access_condition : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : try(v4.attribute_value, null) if !can(regex(local.id_regexp, v4.attribute_value)) && try(v4.attribute_name, null) == "EndPointPolicy"]]]]],
    [for item in local.network_access_condition : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : [for v5 in try(v4.children, []) : try(v5.attribute_value, null) if !can(regex(local.id_regexp, v5.attribute_value)) && try(v5.attribute_name, null) == "EndPointPolicy"]]]]]],
    [for item in local.network_access_condition : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : [for v5 in try(v4.children, []) : [for v6 in try(v5.children, []) : try(v6.attribute_value, null) if !can(regex(local.id_regexp, v6.attribute_value)) && try(v6.attribute_name, null) == "EndPointPolicy"]]]]]]],
    [for item in local.network_access_policy_set : [for v0 in [item] : try(v0.condition_attribute_value, null) if !can(regex(local.id_regexp, v0.condition_attribute_value)) && try(v0.condition_attribute_name, null) == "EndPointPolicy"]],
    [for item in local.network_access_policy_set : [for v1 in try(item.children, []) : try(v1.attribute_value, null) if !can(regex(local.id_regexp, v1.attribute_value)) && try(v1.attribute_name, null) == "EndPointPolicy"]],
    [for item in local.network_access_policy_set : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : try(v2.attribute_value, null) if !can(regex(local.id_regexp, v2.attribute_value)) && try(v2.attribute_name, null) == "EndPointPolicy"]]],
    [for item in local.network_access_policy_set : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : try(v3.attribute_value, null) if !can(regex(local.id_regexp, v3.attribute_value)) && try(v3.attribute_name, null) == "EndPointPolicy"]]]],
    [for item in local.network_access_policy_set : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : try(v4.attribute_value, null) if !can(regex(local.id_regexp, v4.attribute_value)) && try(v4.attribute_name, null) == "EndPointPolicy"]]]]],
    [for item in local.network_access_policy_set : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : [for v5 in try(v4.children, []) : try(v5.attribute_value, null) if !can(regex(local.id_regexp, v5.attribute_value)) && try(v5.attribute_name, null) == "EndPointPolicy"]]]]]],
    [for item in local.network_access_policy_set : [for v1 in try(item.children, []) : [for v2 in try(v1.children, []) : [for v3 in try(v2.children, []) : [for v4 in try(v3.children, []) : [for v5 in try(v4.children, []) : [for v6 in try(v5.children, []) : try(v6.attribute_value, null) if !can(regex(local.id_regexp, v6.attribute_value)) && try(v6.attribute_name, null) == "EndPointPolicy"]]]]]]],
  ])))
  profiler_profile_managed_names   = []
  profiler_profile_unmanaged_names = [for n in local.profiler_profile_referenced_names : n if !contains(local.profiler_profile_managed_names, n)]
}

data "ise_profiler_profile" "profiler_profile" {
  for_each = toset(local.profiler_profile_unmanaged_names)

  name = each.key
}

locals {
  profiler_profile_lookup_ids = { for k, v in data.ise_profiler_profile.profiler_profile : k => v.id }
  profiler_profile_ids = merge(
    local.profiler_profile_lookup_ids,
  )
}
