#
# ################################################################################
#
# This file was automatically generated with ./gen/generate_module.py
#          Do not edit this file directly.
#          More information in repository README.md
#
# ################################################################################
#
terraform {
  required_version = ">= 1.8.0"

  required_providers {
    ise = {
      source  = "CiscoDevNet/ise"
      version = "~> 0.5.0"
    }
    utils = {
      source  = "netascode/utils"
      version = "~> 2.0"
    }
    local = {
      source  = "hashicorp/local"
      version = ">= 2.3.0"
    }
  }
}
